# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

# Loading Dataset

In [2]:
df=pd.read_csv('healthcare-dataset-stroke-data.csv')

In [3]:
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
df.shape

(5110, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [6]:
cols_to_be_object = ["hypertension","heart_disease"]
for col in cols_to_be_object:
    df[col] = df[col].astype("object")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   object 
 4   heart_disease      5110 non-null   object 
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(2), object(7)
memory usage: 479.2+ KB


In [8]:
df.describe()

id          age  avg_glucose_level          bmi       stroke
count   5110.000000  5110.000000        5110.000000  4909.000000  5110.000000
mean   36517.829354    43.226614         106.147677    28.893237     0.048728
std    21161.721625    22.612647          45.283560     7.854067     0.215320
min       67.000000     0.080000          55.120000    10.300000     0.000000
25%    17741.250000    25.000000          77.245000    23.500000     0.000000
50%    36932.000000    45.000000          91.885000    28.100000     0.000000
75%    54682.000000    61.000000         114.090000    33.100000     0.000000
max    72940.000000    82.000000         271.740000    97.600000     1.000000

# Data Cleaning

In [9]:
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [10]:
df['bmi']=df['bmi'].fillna(df['bmi'].median())

In [11]:
df.isna().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
for col in df.columns:
    print(df[col].value_counts())
    print("-*-"*20)

49152    1
21785    1
25982    1
5500     1
28027    1
        ..
45759    1
4795     1
47802    1
49849    1
16380    1
Name: id, Length: 5110, dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
Female    2994
Male      2115
Other        1
Name: gender, dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
78.00    102
57.00     95
52.00     90
54.00     87
51.00     86
        ... 
0.48       3
1.40       3
0.16       3
0.08       2
0.40       2
Name: age, Length: 104, dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
0    4612
1     498
Name: hypertension, dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
0    4834
1     276
Name: heart_disease, dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
Yes    3353
No     1757
Name: ever_married, dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
Private          2925
Self-employed     819
children        

In [14]:
df.head()

id  gender   age hypertension heart_disease ever_married      work_type  \
0   9046    Male  67.0            0             1          Yes        Private   
1  51676  Female  61.0            0             0          Yes  Self-employed   
2  31112    Male  80.0            0             1          Yes        Private   
3  60182  Female  49.0            0             0          Yes        Private   
4   1665  Female  79.0            1             0          Yes  Self-employed   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             202.21  28.1     never smoked       1  
2          Rural             105.92  32.5     never smoked       1  
3          Urban             171.23  34.4           smokes       1  
4          Rural             174.12  24.0     never smoked       1

In [15]:
df["smoking_status"].replace("Unknown", df["smoking_status"].mode().values[0], inplace=True)

In [16]:
df["smoking_status"].value_counts()

never smoked       3436
formerly smoked     885
smokes              789
Name: smoking_status, dtype: int64

# Splitting the data frame into X & Y

In [17]:
X=df.drop(["id","stroke"],axis=1)
X.head()

gender   age hypertension heart_disease ever_married      work_type  \
0    Male  67.0            0             1          Yes        Private   
1  Female  61.0            0             0          Yes  Self-employed   
2    Male  80.0            0             1          Yes        Private   
3  Female  49.0            0             0          Yes        Private   
4  Female  79.0            1             0          Yes  Self-employed   

  Residence_type  avg_glucose_level   bmi   smoking_status  
0          Urban             228.69  36.6  formerly smoked  
1          Rural             202.21  28.1     never smoked  
2          Rural             105.92  32.5     never smoked  
3          Urban             171.23  34.4           smokes  
4          Rural             174.12  24.0     never smoked

In [18]:
Y=df["stroke"]
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: stroke, dtype: int64

In [19]:
categorical_cols = X.select_dtypes("object")
X = pd.get_dummies(X, columns=categorical_cols.columns)

In [20]:
X.head()

age  avg_glucose_level   bmi  gender_Female  gender_Male  gender_Other  \
0  67.0             228.69  36.6              0            1             0   
1  61.0             202.21  28.1              1            0             0   
2  80.0             105.92  32.5              0            1             0   
3  49.0             171.23  34.4              1            0             0   
4  79.0             174.12  24.0              1            0             0   

   hypertension_0  hypertension_1  heart_disease_0  heart_disease_1  ...  \
0               1               0                0                1  ...   
1               1               0                1                0  ...   
2               1               0                0                1  ...   
3               1               0                1                0  ...   
4               0               1                1                0  ...   

   work_type_Govt_job  work_type_Never_worked  work_type_Private  \
0                   0                       0                  1   
1                   0                       0                  0   
2                   0                       0                  1   
3                   0                       0                  1   
4                   0                       0                  0   

   work_type_Self-employed  work_type_children  Residence_type_Rural  \
0                        0                   0                     0   
1                        1                   0                     1   
2                        0                   0                     1   
3                        0                   0                     0   
4                        1                   0                     1   

   Residence_type_Urban  smoking_status_formerly smoked  \
0                     1                               1   
1                     0                               0   
2                     0                               0   
3                     1                               0   
4                     0                               0   

   smoking_status_never smoked  smoking_status_smokes  
0                            0                      0  
1                            1                      0  
2                            1                      0  
3                            0                      1  
4                            1                      0  

[5 rows x 22 columns]

# Splitting the Data into Train, Test Datasets

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [22]:
X_train.shape,Y_train.shape

((4088, 22), (4088,))

In [23]:
X_test.shape,Y_test.shape

((1022, 22), (1022,))

# Build Classification Algorithm

### Logistic Regression 

In [24]:
LR=LogisticRegression(solver='liblinear',multi_class='ovr')
LR.fit(X_train,Y_train)
LR_pred = LR.predict(X_test)

In [25]:
c_m=confusion_matrix(LR_pred,Y_test)
print(c_m)

[[960  62]
 [  0   0]]


In [26]:
print('accuracy of logistic regression = ', metrics.accuracy_score(LR_pred,Y_test)*100)

accuracy of logistic regression =  93.9334637964775


### KNN

In [27]:
#Finding the value of K
import math
k=math.sqrt(len(Y_train))
print(k)

63.93746945258312


In [28]:
knn=KNeighborsClassifier(n_neighbors=65,p=2,metric="euclidean")
knn.fit(X_train,Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=65)

In [29]:
knn_pred=knn.predict(X_test)
c_m=confusion_matrix(knn_pred,Y_test)
print(c_m)

[[960  62]
 [  0   0]]


In [30]:
print('accuracy of KNN = ',metrics.accuracy_score(knn_pred,Y_test)*100)

accuracy of KNN =  93.9334637964775


### Random Forest

In [31]:
r_c=RandomForestClassifier(n_estimators=100 , criterion = 'entropy', random_state = 0)
r_c.fit(X_train, Y_train)
rc_pred = r_c.predict(X_test)
c_m = confusion_matrix(rc_pred,Y_test)

In [32]:
print(c_m)

[[960  61]
 [  0   1]]


In [33]:
print("Accuracy of Random Forest:",metrics.accuracy_score(Y_test, rc_pred)*100)

Accuracy of Random Forest: 94.03131115459882


### SVM

In [34]:
svm = SVC()
svm.fit(X_train, Y_train)
svm_pred = svm.predict(X_test)

In [35]:
c_m=confusion_matrix(Y_test,svm_pred)
print(c_m)

[[960   0]
 [ 62   0]]


In [36]:
print("Accuracy of SVM:",metrics.accuracy_score(Y_test,svm_pred)*100)

Accuracy of SVM: 93.9334637964775


# Naive Bayes 

In [37]:
n_b=GaussianNB()
n_b.fit(X_train,Y_train)
n_b_pred=n_b.predict(X_test)
confusionmatrix=confusion_matrix(n_b_pred,Y_test)
print(confusionmatrix)

[[562   4]
 [398  58]]


In [38]:
print('accuracy = ',metrics.accuracy_score(n_b_pred,Y_test)*100)

accuracy =  60.665362035225044
